### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/ri-collection-explicit-feedback-twitter#1]
Hi,

I had follow steps and when I call these web services I get "404 page not found" response.

Request:
`IP:9624/mention/ibercivis/lang/es/fast`
Response: 
`404 page not found`

Am I doing something wrong? Can you help me?

**Comment by ChristophStanik** [comment]
Hi,

I guess you added the Twitter tokens as described? 
Could you please try to modify the call as follows and come back to me with the result?

`IP:9624/hitec/crawl/tweets/mention/ibercivis/lang/es/fast`

**Comment by vvalvesga** [comment]
ok, it works!

Thanks
